export enum UserType {
  PLATFORM_ADMIN = "PLATFORM_ADMIN",
  CONTRACTOR = "CONTRACTOR",
  HOME_OWNER = "HOME_OWNER",
}

export enum ServiceCategory {
  PLUMBING = "PLUMBING",
  ELECTRICAL = "ELECTRICAL",
  GARDENING_AND_LANDSCAPING = "GARDENING_AND_LANDSCAPING",
  CARPENTRY = "CARPENTRY",
}
