export enum UserType {
  PLATFORM_ADMIN = "PLATFORM_ADMIN",
  CONTRACTOR = "CONTRACTOR",
  HOME_OWNER = "HOME_OWNER",
}

export enum UserStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  SUSPENDED = "SUSPENDED",
  PENDING = "PENDING",
}

export enum ServiceCategory {
  PLUMBING = "PLUMBING",
  ELECTRICAL = "ELECTRICAL",
  GARDENING_AND_LANDSCAPING = "GARDENING_AND_LANDSCAPING",
  CARPENTRY = "CARPENTRY",
}
